-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 14:29:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_vendas` DEFAULT CHARACTER SET utf8 ;
USE `dw_vendas` ;

-- -----------------------------------------------------
-- Table `dw_vendas`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_vendas`.`DIM_CLIENTE` (
  `id_cliente` INT NOT NULL,
  `nm_completo` VARCHAR(150) NULL,
  `tp_sexo` VARCHAR(25) NULL,
  `nr_idade` INT NULL,
  `estado_civil` VARCHAR(25) NULL,
  `nr_filhos` INT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_vendas`.`DIM_LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_vendas`.`DIM_LOJA` (
  `id_loja` INT NOT NULL,
  `nm_loja` VARCHAR(100) NULL,
  `qt_colaborador` INT NULL,
  `tp_loja` VARCHAR(50) NULL,
  `pais` VARCHAR(100) NULL,
  `continente` VARCHAR(100) NULL,
  PRIMARY KEY (`id_loja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_vendas`.`DIM_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_vendas`.`DIM_PRODUTO` (
  `id_produto` VARCHAR(25) NOT NULL,
  `nm_produto` VARCHAR(120) NULL,
  `nm_marca` VARCHAR(100) NULL,
  `tp_produto` VARCHAR(50) NULL,
  `vl_preco` DECIMAL(8,2) NULL,
  `vl_custo` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_vendas`.`DIM_TEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_vendas`.`DIM_TEMPO` (
  `dt_referencia` DATE NOT NULL,
  `ano` INT NULL,
  `trimestre` INT NULL,
  `dia` INT NULL,
  `mes` VARCHAR(50) NULL,
  `dia_da_semana` VARCHAR(50) NULL,
  `flag_feriado` TINYINT NULL,
  PRIMARY KEY (`dt_referencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_vendas`.`FATO_VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_vendas`.`FATO_VENDAS` (
  `id_venda` VARCHAR(50) NOT NULL,
  `id_cliente` INT NULL,
  `id_produto` VARCHAR(25) NULL,
  `id_loja` INT NULL,
  `dt_venda` DATE NULL,
  `vl_venda` DECIMAL(8,2) NULL,
  `nm_produto` VARCHAR(120) NULL,
  `tp_produto` VARCHAR(100) NULL,
  `ano_venda` INT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `loja_idx` (`id_loja` ASC) VISIBLE,
  INDEX `cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `produto_idx` (`id_produto` ASC) VISIBLE,
  INDEX `tempo_idx` (`dt_venda` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `dw_vendas`.`DIM_CLIENTE` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `loja`
    FOREIGN KEY (`id_loja`)
    REFERENCES `dw_vendas`.`DIM_LOJA` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `dw_vendas`.`DIM_PRODUTO` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tempo`
    FOREIGN KEY (`dt_venda`)
    REFERENCES `dw_vendas`.`DIM_TEMPO` (`dt_referencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
